import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const browser=await chromium.launch({channel:'msedge',headless:true})
const id='11dFghVXANMlKmJXsNCbNl'
try {
  fs.mkdirSync('../docs/screenshots',{recursive:true})
  const context=await browser.newContext({viewport:{width:1365,height:1000}})
  // Avoid depending on third-party playback/network in this deterministic UI test.
  await context.route('https://open.spotify.com/embed/**',route=>route.fulfill({contentType:'text/html',body:'<p>Spotify iframe fixture (UI test)</p>'}))
  const page=await context.newPage(), errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  page.setDefaultTimeout(15000)
  await page.goto(process.env.SMOKE_ADMIN)
  await page.locator('#admin-login-form [name=identifier]').fill('browser_admin@test.invalid')
  await page.locator('#admin-login-form [name=password]').fill(process.env.SMOKE_PASSWORD)
  await page.locator('#admin-login-form button').click()
  await page.locator('[data-tab=genres]').click()
  assert.equal(await page.locator('.topbar input').count(),0)
  assert.equal(await page.locator('[data-genre-type=Movie]').getAttribute('aria-selected'),'true')
  assert.equal(await page.locator('tbody tr:visible').count(),3)
  await page.locator('[data-genre-type=Song]').click()
  assert.equal(await page.locator('tbody tr:visible').count(),12)
  await page.locator('[data-next]').click()
  assert.equal(await page.locator('tbody tr:visible').count(),12)
  await page.locator('.list-controls [name=search]').fill('Test genre 24')
  assert.equal(await page.locator('tbody tr:visible').count(),1)
  await page.locator('.list-controls [name=search]').fill('')
  await page.locator('[data-genre-type=Movie]').click()
  assert.equal(await page.locator('tbody tr:visible').count(),3)
  await page.locator('.list-controls [name=sort]').selectOption('za')
  assert.ok((await page.locator('tbody tr:visible').first().innerText()).includes('Sci-Fi'))
  await page.locator('[data-genre-type=Song]').click()
  await page.locator('.list-controls [name=search]').fill('no matching genre')
  assert.equal(await page.locator('tbody tr:visible').count(),0)
  assert.equal(await page.locator('.list-empty').isVisible(),true)
  // Real OMDb lookup and CRUD against the isolated test database.
  await page.locator('[data-tab=movies]').click()
  await page.locator('[data-action=add]').click()
  await page.locator('[data-omdb-query]').fill('tt3896198')
  await page.locator('[data-omdb]').click()
  await page.locator('[data-omdb-status]').filter({hasText:'Autofilled:'}).waitFor({timeout:25000})
  assert.equal(await page.locator('#editor-form [name=imdbId]').inputValue(),'tt3896198')
  await page.waitForFunction(()=>document.querySelector('#editor-form [name=valence]').value!=='')
  assert.equal(await page.locator('#editor-form [name=moodSource]').inputValue(),'genre-default')
  await page.locator('#editor-form [name=valence]').fill('0.91')
  await page.locator('#editor-form [name=arousal]').fill('-0.21')
  await page.locator('[data-omdb]').click()
  await page.locator('[data-omdb-status]').filter({hasText:'Autofilled:'}).waitFor({timeout:25000})
  assert.equal(await page.locator('#editor-form [name=valence]').inputValue(),'0.91')
  const movieTitle=await page.locator('#editor-form [name=title]').inputValue()
  assert.ok(movieTitle.includes('Guardians'))
  await page.locator('[data-action=save]').click()
  await page.locator('#editor-form').waitFor({state:'detached'})
  const savedMovies=await page.evaluate(async()=>await (await fetch('/api/Movies')).json())
  assert.ok(savedMovies.find(x=>x.tieuDe===movieTitle)?.updatedAt)
  const movieRow=page.locator('tbody tr').filter({hasText:movieTitle})
  await movieRow.locator('[data-action=edit]').click()
  assert.equal(await page.locator('#editor-form [name=imdbId]').inputValue(),'tt3896198')
  assert.ok((await page.locator('#editor-form [name=description]').inputValue()).length>20)
  assert.equal(await page.locator('#editor-form [name=valence]').inputValue(),'0.91')
  assert.equal(await page.locator('#editor-form [name=moodSource]').inputValue(),'manual')
  await page.locator('#editor-form [name=title]').fill(movieTitle+' test edit')
  await page.locator('[data-action=save]').click()
  await page.locator('#editor-form').waitFor({state:'detached'})
  await page.locator('tbody tr').filter({hasText:movieTitle+' test edit'}).waitFor()
  await page.locator('[data-tab=music]').click()
  await page.locator('[data-music-info]').first().click()
  assert.equal(await page.locator('.music-dialog [data-play]').count(),0)
  const frame=page.locator('.music-dialog iframe')
  await frame.waitFor()
  assert.equal(await page.locator('.music-dialog a').count(),1)
  assert.equal(await page.locator('.music-detail-grid').count(),1)
  assert.equal(await frame.getAttribute('src'),'https://open.spotify.com/embed/track/'+id)
  await page.screenshot({path:'../docs/screenshots/music-details-compact.png'})
  await page.locator('.music-dialog [data-close]').click()
  assert.equal(await page.locator('iframe').count(),0)
  assert.equal(await page.locator('[data-tab=spotify]').count(),0)
  // Exercise actionable provider failure without exposing a token or logging the admin out.
  await page.route('**/api/Spotify/status',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'premium_required',message:'Spotify requires an active Premium subscription for the app owner.'})}))
  await page.locator('[data-action=add]').click()
  await page.locator('#spotify-connection.is-disconnected').waitFor()
  assert.ok((await page.locator('#spotify-connection').innerText()).includes('check your account'))
  assert.equal(await page.locator('#spotify-label-mode, #spotify-genre, #spotify-status').count(),0)
  await page.locator('.spotify-import-dialog .close-button').click()
  await page.unroute('**/api/Spotify/status')
  await page.route('**/api/Spotify/status',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({connected:true})}))
  await page.locator('[data-action=add]').click()
  await page.locator('#spotify-connection.is-connected').waitFor()
  assert.equal(await page.locator('#admin-login-form').count(),0)
  await page.route('**/api/Spotify?*',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({
    items:[{externalId:id,title:'Spotify fixture song',artists:'Fixture artist',duration:180,album:'Fixture album',releaseDate:'2020-01',sourceUrl:'https://open.spotify.com/track/'+id}],importedIds:[]})}))
  await page.locator('#spotify-search input').fill('Fixture')
  await page.locator('#spotify-search button').click()
  await page.locator('[data-song]').waitFor()
  await page.locator('[data-song]').check()
  await page.locator('#spotify-import').click()
  await page.locator('[role=alert]').filter({hasText:'Select songs and a mood'}).waitFor()
  await page.locator('#spotify-mood').selectOption({label:'Happy'})
  let payload
  await page.route('**/api/Spotify/import',async route=>{
    payload=route.request().postDataJSON()
    await route.fulfill({contentType:'application/json',body:JSON.stringify({items:[{externalId:id,status:'existing',contentId:'SPOTIFY_'+id,message:'Already imported'}]})})
  })
  await page.locator('#spotify-import').click()
  await page.locator('[data-song]:disabled').waitFor()
  assert.deepEqual(payload.songIds,[id]);assert.ok(payload.tamTrangID>0)
  await page.locator('[data-preview]').click()
  await page.locator('#spotify-preview iframe').waitFor()
  await page.screenshot({path:'../docs/screenshots/spotify-admin-fixture.png',fullPage:true})
  await page.keyboard.press('Escape')
  await page.locator('.spotify-import-dialog').waitFor({state:'detached'})
  await page.locator('[data-tab=overview]').click()
  assert.equal(await page.locator('iframe').count(),0)
  assert.deepEqual(errors,[])
  console.log('PASS: admin Spotify UI (fixture search/import/player), real login/catalog/mood APIs, Premium error, required mood, duplicate state and player cleanup.')
  await context.close()
} finally { await browser.close() }
